version: 2.1

orbs:
  python: circleci/python@1.5.0

jobs:
  build-and-test:
    docker:
      - image: cimg/python:3.10.2
    executor: python/default
    steps:
      - run:
          name: Install Packages
          command: 
            COPY ../requirements.txt /tmp/
            RUN pip install --requirement /tmp/requirements.txt
      - run:
          command: python3 -m pytest
          name: Test

workflows:
  main:
    jobs:
      - build-and-test
